#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the shell to run this script:
#           ksh Gradle
#       Or, if you have a compliant shell, just run:
#           ./gradlew
#
#   (2) This script attempts to find a defined JAVA_HOME to run java. If you
#       have Java installed in a non-standard location, you must set the JAVA_HOME
#       environment variable.
#
#   (3) This script attempts to find a defined GRADLE_USER_HOME to store
#       gradle-related files. If it is not set, the script uses a directory
#       .gradle in the user's home directory. At the beginning of a Gradle build,
#       the script calls 'init' to create the `.gradle` directory in the appropriate
#       location.
#
#   (4) By default, Gradle uses the lowest priority of all of the following JVM
#       heap sizes, in order: from the value of GRADLE_OPTS, JAVA_OPTS, -Xmx,
#       -XX:MaxMetaspaceSize, then the value in the properties file.
#       So, try increasing the heap size. For example, to set the maximum heap
#       size to 1GB, you can edit the gradle.properties file to add the following
#       line:
#           org.gradle.jvmargs=-Xmx1024m
#
#       Or, you can pass it in from the command-line:
#           ./gradlew -Xmx1024m
#
#   (5) If you ever see a 'permission denied' error, you should run this script
#       again with the 'exec' prefix (e.g. 'exec ./gradlew').
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not supported. Apple's zsh does. Go figure...
        # We use 'ulimit -n -H' if it seems to work, otherwise we error.
        # We have to redirect stderr because both commands write to stderr,
        # and they first delete the old ulimit value. This seems to work
        # regardless of the order. stdout is untouched (and preserved for
        # later command output).
        #
        # Keep in mind that the 'head' command might not be POSIX compliant,
        # but it seems to be on all platforms we currently support.
        #
        # The 'ulimit' command might not be available on platforms like ZOS,
        # so we have to try/catch.
        #
        # We cannot use a subshell for 'head' because the pipeline doesn't inherit
        # the exit code of a pipe that uses '!' (negation) in POSIX.
        #
        # In dash (and other shells), 'head -n -1' isn't supported. We need to
        # use 'head -n -1' only if we know it works. We know it works on
        # shells with pipefail support (bash, zsh, and maybe others?), but we
        # cannot easily check for pipefail support.
        #
        # Limitation: In zsh, 'head -n -1' fails with a numeric error if the
        # pipeline doesn't produce any output. We must therefore check for
        # output first.
        #
        # In some shells, 'ulimit -n -H' fails with a numeric error that indicates
        # that there is no hard limit. We'll catch it.
        #
        if test -n "$(ulimit -n -H 2>/dev/null)"; then
            # Found a hard limit that we can use.
            MAX_FD=$(ulimit -n -H)
        else
            # Not found, try the POSIX compliant hard limit name (might be
            # something else, like 'hard').
            for hard_limit in rlim_fd_cur hard; do
                if test -n "$(ulimit -n -H -r -c -s -t -u -v -i 2>/dev/null | grep "$hard_limit")"; then
                    MAX_FD=$(ulimit -n -H | grep "$hard_limit" | awk '{print $NF}')
                    break
                fi
            done
        fi
        ;;
      *)
        MAX_FD=$(ulimit -n -H 2>/dev/null) || warn "Could not query maximum file descriptor limit"
    esac
fi

# Solaris sh lacks 'wait' builtin, but we can use 'wait' as a function.
# We need to avoid calling a function named 'wait' from within the script
# because that can clash with a built-in wait in e.g. Bash.
# Also, POSIX 'wait' is a shell built-in, but we cannot rely on it being
# available (this is true for ksh).
# For that reason, we use a fallback to a plain 'wait' function (as long as it
# doesn't take any argument) because that works even if the shell's 'wait' is
# not a built-in but a function.
wait_for_pid () {
    if test -z "$1"; then
        return 1
    fi

    # If 'wait' is a function, use the fallback (or maybe the function is the
    # built-in wait, but at that point it's better to use the function).
    if ! command -v wait >/dev/null || ! wait "$1" 2>/dev/null; then
        # Fallback to using 'kill' to check the process status.
        while true; do
            if kill -0 "$1" 2>/dev/null; then
                # Process still running.
                sleep 1
            else
                # Process is gone.
                break
            fi
        done
    fi
}

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - we need to take care about a leading "-D"
    # and arguments that look like "value" (with spaces).
    # We cannot use IFS as we want to keep spaces in arguments (if any).
    # There's no quotes around the arguments, so we cannot rely on the
    # shell to take care of it.
    # Instead, we iterate and transform.
    for i in "$@"; do
        case "$i" in
            -D*)
                # Handle arguments that start with -D (Java properties).
                # Need to preserve the dash, the key, and the value.
                # The value may contain spaces, so we can't rely on splitting.
                # The value may contain the '=' character, which we want to preserve.
                # We'll just remove the quotes (if present).
                # Use 'sed' to remove the quotes.
                # We can't use 'tr' because it would replace the '=' as well.
                # Remove the first and last quote (if present).
                # Check if the first character is a quote.
                # Fast-forward to first '='.
                # Since the argument is in the variable, we can't use parameter expansion.
                # Instead, we'll use 'cut' to split at '='.
                # This does not support values containing '='.
                # The 'cut' command splits at '=', but only for the first.
                # That should be fine because there is only one '=' in Java properties.
                key=$(echo "$i" | cut -d '=' -f 1)
                value=$(echo "$i" | cut -d '=' -f 2-)
                # Remove the first and last quote (if present) from the value.
                # First, check if the first char is a quote.
                # value="${value%\"}" also works, but we need to preserve quotes.
                # Use 'sed' to remove the first and last quote.
                # The quote may be escaped.
                value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
                # Rebuild the argument.
                i="$key=$value"
                ;;
        esac
        # Escape the string for Java.
        # In some shells, we cannot do that reliably, so we rely on the
        # variable not needing to be escaped.
        # shellcheck disable=SC2086
        set -- "$@" "$i"
    done
fi

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

# We use the extra "org.gradle.jvmargs" setting to set the maximum heap size.
# That is set in gradle.properties, but for older Gradle versions, we need to
# set it explicitly.
# Usually, we can just set the GRADLE_OPTS.
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G"
fi

# For Cygwin, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - we need to take care about a leading "-D"
    # and arguments that look like "value" (with spaces).
    # We cannot use IFS as we want to keep spaces in arguments (if any).
    # There's no quotes around the arguments, so we cannot rely on the
    # shell to take care of it.
    # Instead, we iterate and transform.
    for i in "$@"; do
        case "$i" in
            -D*)
                # Handle arguments that start with -D (Java properties).
                # Need to preserve the dash, the key, and the value.
                # The value may contain spaces, so we can't rely on splitting.
                # The value may contain the '=' character, which we want to preserve.
                # We'll just remove the quotes (if present).
                # Use 'sed' to remove the quotes.
                # We can't use 'tr' because it would replace the '=' as well.
                # Remove the first and last quote (if present).
                # Check if the first character is a quote.
                # Fast-forward to first '='.
                # Since the argument is in the variable, we can't use parameter expansion.
                # Instead, we'll use 'cut' to split at '='.
                # This does not support values containing '='.
                # The 'cut' command splits at '=', but only for the first.
                # That should be fine because there is only one '=' in Java properties.
                key=$(echo "$i" | cut -d '=' -f 1)
                value=$(echo "$i" | cut -d '=' -f 2-)
                # Remove the first and last quote (if present) from the value.
                # First, check if the first char is a quote.
                # value="${value%\"}" also works, but we need to preserve quotes.
                # Use 'sed' to remove the first and last quote.
                # The quote may be escaped.
                value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
                # Rebuild the argument.
                i="$key=$value"
                ;;
        esac
        # Escape the string for Java.
        # In some shells, we cannot do that reliably, so we rely on the
        # variable not needing to be escaped.
        # shellcheck disable=SC2086
        set -- "$@" "$i"
    done
fi

# We use the extra "org.gradle.jvmargs" setting to set the maximum heap size.
# That is set in gradle.properties, but for older Gradle versions, we need to
# set it explicitly.
# Usually, we can just set the GRADLE_OPTS.
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G"
fi

# For Cygwin, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - we need to take care about a leading "-D"
    # and arguments that look like "value" (with spaces).
    # We cannot use IFS as we want to keep spaces in arguments (if any).
    # There's no quotes around the arguments, so we cannot rely on the
    # shell to take care of it.
    # Instead, we iterate and transform.
    for i in "$@"; do
        case "$i" in
            -D*)
                # Handle arguments that start with -D (Java properties).
                # Need to preserve the dash, the key, and the value.
                # The value may contain spaces, so we can't rely on splitting.
                # The value may contain the '=' character, which we want to preserve.
                # We'll just remove the quotes (if present).
                # Use 'sed' to remove the quotes.
                # We can't use 'tr' because it would replace the '=' as well.
                # Remove the first and last quote (if present).
                # Check if the first character is a quote.
                # Fast-forward to first '='.
                # Since the argument is in the variable, we can't use parameter expansion.
                # Instead, we'll use 'cut' to split at '='.
                # This does not support values containing '='.
                # The 'cut' command splits at '=', but only for the first.
                # That should be fine because there is only one '=' in Java properties.
                key=$(echo "$i" | cut -d '=' -f 1)
                value=$(echo "$i" | cut -d '=' -f 2-)
                # Remove the first and last quote (if present) from the value.
                # First, check if the first char is a quote.
                # value="${value%\"}" also works, but we need to preserve quotes.
                # Use 'sed' to remove the first and last quote.
                # The quote may be escaped.
                value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
                # Rebuild the argument.
                i="$key=$value"
                ;;
        esac
        # Escape the string for Java.
        # In some shells, we cannot do that reliably, so we rely on the
        # variable not needing to be escaped.
        # shellcheck disable=SC2086
        set -- "$@" "$i"
    done
fi

# We use the extra "org.gradle.jvmargs" setting to set the maximum heap size.
# That is set in gradle.properties, but for older Gradle versions, we need to
# set it explicitly.
# Usually, we can just set the GRADLE_OPTS.
if [ -z "$GRADLE_OPTS" ]; then
    GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2G"
fi

# For Cygwin, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - we need to take care about a leading "-D"
    # and arguments that look like "value" (with spaces).
    # We cannot use IFS as we want to keep spaces in arguments (if any).
    # There's no quotes around the arguments, so we cannot rely on the
    # shell to take care of it.
    # Instead, we iterate and transform.
    for i in "$@"; do
        case "$i" in
            -D*)
                # Handle arguments that start with -D (Java properties).
                # Need to preserve the dash, the key, and the value.
                # The value may contain spaces, so we can't rely on splitting.
                # The value may contain the '=' character, which we want to preserve.
                # We'll just remove the quotes (if present).
                # Use 'sed' to remove the quotes.
                # We can't use 'tr' because it would replace the '=' as well.
                # Remove the first and last quote (if present).
                # Check if the first character is a quote.
                # Fast-forward to first '='.
                # Since the argument is in the variable, we can't use parameter expansion.
                # Instead, we'll use 'cut' to split at '='.
                # This does not support values containing '='.
                # The 'cut' command splits at '=', but only for the first.
                # That should be fine because there is only one '=' in Java properties.
                key=$(echo "$i" | cut -d '=' -f 1)
                value=$(echo "$i" | cut -d '=' -f 2-)
                # Remove the first and last quote (if present) from the value.
                # First, check if the first char is a quote.
                # value="${value%\"}" also works, but we need to preserve quotes.
                # Use 'sed' to remove the first and last quote.
                # The quote may be escaped.
                value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')
                # Rebuild the argument.
                i="$key=$value"
                ;;
        esac
        # Escape the string for Java.
        # In some shells, we cannot do that reliably, so we rely on the
        # variable not needing to be escaped.
        # shellcheck disable=SC2086
        set -- "$@" "$i"
    done
fi

exec "$JAVACMD" "$@"
